apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167828989
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167828989
    app.kubernetes.io/part-of: test-app-167828989
  name: java-quarkus-167828989
  namespace: 6b5wha1j-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-167828989
status:
  loadBalancer: {}
